### ISSUE TITLE
The gift functionality in product page

### ISSUE THREAD

**Issue by regis-samurai** [vtex-apps/store-discussion#174]
**What are you trying to accomplish? Please describe.**  
I'm developing a theme that needs a gift feature on the product page. Today, in VTEX IO, is there this feature?

**What have you tried so far?**  
I believed that application the product kit was responsible for this, but it is only responsible for the buy-together functionality.

**Additional info** 
I'm making migration this store to vtex io, this product exists the buy-together functionality
https://pentruanimale.ro/hrana-uscata-caini/royal-canin-maxi-adult-15kg-1.html

| Account | Workspace |
|---|---|
|`pentruanimale`|`samurai`|

**Comment by klzns** [comment]
We don't have that yet.

How do you imagine this block working?

**Comment by regis-samurai** [comment]
> We don't have that yet.
> 
> How do you imagine this block working?

The Gift is a Promotion that allow the Store to give a specific SKU  when a product is bought for this  Pentru Animale should create a Promotion under Rates and Benefits  with the discount type GIFT.

The gift must be a product registered on VTEX .
After adding the SKU, Pentru animal will be able to select the conditions for the gift to be given (Category, Products, Brands, Collections per example)

When a customer add a product that contains a gift, the gift will be added on cart without any extra cost.

On JSON File  that integrates the Order with the ERP contains a line with the name  "isGift": True, when an item is a Gift, On the marketing data will receive also the campain that generated the gift


This is a section of the project document written by Diego Cione.

**Comment by klzns** [comment]
That's good information.

But how do you imagine a block like "product-gift" or something like that working? My question is: what can we provide for you to achieve the layout you want.

**Comment by regis-samurai** [comment]
The vtex io team can make an application as a product gift, which can be called on the product page. I think it's a feature that other stores would like.
The expected behavior is like the product kit application, but with another kind of promotion.

Maybe you can update the product kit code to accept the promotion type, and we may call with different behaviors. I don't know the best way.

Store with gift:
https://www.epocacosmeticos.com.br/birt-rhythm-floral-eau-de-toilette-burberry-kit-perfume-feminino-50ml-locao-corporal-75ml/p

Vtex CMS Controller:
<vtex.cmc:ProductGifts />

**Comment by klzns** [comment]
Benchmarks:
- [Epoca](https://www.epocacosmeticos.com.br/birt-rhythm-floral-eau-de-toilette-burberry-kit-perfume-feminino-50ml-locao-corporal-75ml/p)
- [Beauty Box](https://www.beautybox.com.br/acelerador-de-bronzeado-australian-gold-spray-gel-instant-bronzer_821309/p?skuId=20333)
- [Beauty Box more than one](https://www.beautybox.com.br/perfume-miss-dior-blooming-bouquet-feminino-eau-de-toilette_807566-p/p?skuId=7587)
- [Pentru Animale](https://pentruanimale.ro/hrana-uscata-caini/royal-canin-maxi-adult-15kg-1.html)
- [Beleza na Web](https://www.belezanaweb.com.br/ch-carolina-herrera-eau-de-toilette-perfume-feminino-100ml/)
- [Shop Luxo](https://www.shopluxo.com.br/nina-ricci-collector-bella-eau-de-toilette-feminino-29334/p)

**Comment by klzns** [comment]
![image](https://user-images.githubusercontent.com/284515/73297414-4d1b2a00-41ea-11ea-98f0-2e5656e52aec.png)

```js
{
  "product-gifts": {
    "props": {
      "maxVisibleItems": 1
    },
    "children": [
      "rich-text#gift",
      "product-gift-text",
      "product-gift-list"
    ]
  },
  "product-gift-list":{
    "children": [
      "gift-name",
      "gift-image"
    ]
  },
  "rich-text#gift": {
    "props": {
      "blockClass": "gift",
      "text": "+ Brinde!"
    }
  },
  "product-gift-text": {
    "props": {
      "text": "{exceedingItems, plural, =0{} other {+ {exceedingItems, plural, one {brinde} other {brindes}}}"
    }
  }
}
```

**Comment by klzns** [comment]
Blocks available:

```yam
product-gifts
  props:
    maxVisibleItems: number
  children: any[]

product-gift-list
  children: any[]

gift-name

gift-image

gift-description

product-gift-text
  props:
    label: TranslatableText
```

## `product-gifts`

This block provide the necessary context for other blocks. So, it should be above in the hierarchy of: `product-gift-list` and `product-gift-text`.

Prop | Description
---|---
`maxVisibleItems` | Maximum number of gifts to be rendered by `product-gift-list`

## `product-gift-list`

Responsible for rendering the list of gifts. It uses the prop children to render each gift. Example:

```jsx
return (
  <div className="gift-list">
    {gifts.map(gift => <GiftItem gift={gift}>{children}</GiftItem>
  </div>
```

GiftItem is a React component that provides the context for other blocks (`gift-name`, `gift-image` and `gift-description`).

## `gift-name`

Renders the name of the gift

## `gift-image`

Renders the image of the gift

## `gift-description`

Renders the description of the gift **(check if we have that info)**

 ## `product-gift-text`

This block makes it possible to render any text that need info of the gifts context.

Props | Description
---|---
`label` | A translatable string that have variables that might be used to render any text regarding the gifts


The variables available to `label`:

Variable name | Description
---|---
`totalGifts` | Number of gifts available
`exceedingItems`| Number of items that were not rendered because of the `maxVisibleItems` prop of `product-gifts`.
`visibleItems` | Number of items that were rendered because of the `maxVisibleItems` prop of `product-gifts`.
