### ISSUE TITLE
Shelf is having trouble resizing

### ISSUE THREAD

**Issue by TejadaDriven** [vtex-apps/store-discussion#183]
**Describe the bug**
The shelf is sizing the items as if it can fit two items, when in reality it should be just one, thus causing the product-summary inside to be smaller than it should and causing overflow issues. It was working as intended for a long time but recently it seems to have broken, the issue can be reproduced even if I disable all custom styles.

**To Reproduce**
1. On a mobile device, or using Chrome's emulator, go to https://newrelease--paguemenos.myvtex.com/
2. Scroll down to a shelf, like the "Ofertas em Destaque" one

**Expected behavior**
Show only one item (because minItemsPerPage is set to 1) on mobile screens and never set a size that's smaller than the content.

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/58556436/73184221-d8b58d80-40fa-11ea-846e-d716c75707f7.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Max
 - OS: iOS 13.3
 - Browser Chrome

**Additional context**
Block configuration for the first shelf (all the others are similar)
```
  "shelf#home-1": {
    "blocks": [
      "product-summary.shelf"
    ],
    "props": {
      "orderBy": "OrderByTopSaleDESC",
      "productList": {
        "maxItems": 8,
        "arrows": true,
        "titleText": "Ofertas em Destaque",
        "minItemsPerPage": 1,
        "itemsPerPage": 4
      }
    }
  },
```

**Comment by victorhmp** [comment]
Hi @TejadaDriven! Thanks for opening this issue :)

Trying to reproduce the described behavior, I opened the workspace you sent using Firefox. The shelf looks fine, but the page still overflows on the x-axis. The cause of this overflow is actual the image (from this src: https://paguemenosqa.vteximg.com.br/arquivos/pm-sempre-bem.png) that is causing the page to overflow, which makes the Shelf component think it has more space than it should.

I then opened this on Chrome and observed the exact behavior you described. But, when I simply deleted the flex-layout.col containing the image, the overflow was gone. Then, any interaction with the shelf should make it normal again. This leads me to think that the real issue is not in the Shelf component, but in the store's theme.

Try the following steps to reproduce:
- Open dev tools on Chrome
- Inspect the flex-col that contains the whole section with the image and delete it from the DOM tree. The overflow should be gone.
- Interact with the shelf and it should go back to normal.
