### ISSUE TITLE
Bug: Problem uploading GIF images to Storefront

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#20]
**Describe the bug**
GIF images are loosing animation when uploaded to Storefront

**To Reproduce**
1. Go to Storefront;
2. Edit an element that supports image upload like a Carousel;
3. Upload animated GIF file;
4. See that the image looses its animation properties;

**Expected behavior**
Uploading animated GIFs should retain animation data;

**Comment by hapoza** [comment]
@brunojdo Had told me that they're not going to allow GIF's, it's vtex.file-manager-graphql that strips the frames from the file, because GIF's are very large and would negatively impact the website performance.
The ideal case that he mentioned, is for vtex.file-manager-graphql to allow upload of videos, and following this best practice for animated images as videos https://web.dev/replace-gifs-with-videos
But for that to work, the "image renderers" all should be updated to render self playing videos (like image, carousel, info-card).

I already have an issue with the same discussion https://github.com/vtex-apps/file-manager-graphql/issues/4

Workarounds for now could be to use rich-text or sandbox, but that doesn't work for all cases (like carousel)

**Comment by fpsman** [comment]
I think this approach is too aggressive, a lot of big e-commerce use gifs as medium type. For example Americanas.com, Dafiti:
https://images-americanas.b2w.io/spacey/2019/07/01/semana-tec_ESTRELA_28-06_02-CEEEERTO.gif
https://dafitistatic-a.akamaihd.net/cms/onsite/2017/HomeNeutra_285x155_Socialmedia_110717.gif

This image above only has ~100kb.

I don't know if the market is prepared to this mindset, maybe it should be considered in a future release as a Major of the StoreFront, allowing stores to migrate to this new paradigm after it's mature enough.

**Comment by fpsman** [comment]
Maybe the solution is limit the file update maximum size more than block gifs

**Comment by klzns** [comment]
I think we should accept GIFs as upload files and transform them to mp4 or WebM in our backend. 

As suggested here: https://web.dev/replace-gifs-with-videos

**Comment by saviofelixmuniz** [comment]
We do have a way of displaying GIFs in the store, although not recommended nowadays for performance issues, like pointed previously. You guys could use the [Image component](https://github.com/vtex-apps/store-components/tree/master/react/components/Image) and use the src prop to point to a gif image.

**Comment by klzns** [comment]
Fixed some time ago
