### ISSUE TITLE
RFC: Slots

### ISSUE THREAD

**Issue by victorhmp** [vtex-apps/store-discussion#213]
# Slots

We are trying to simplify the distinction between `blocks` and `children` used to configure blocks.
Our users should not have to learn the concepts of `composition`, `allowed` and how a `blocks` arrays differ from `children`.  Also, we should not plan for extensibility of components based on placing a certain block into a certain slot in the parent component, but rather placing *any* block into that slot.

## Proposed solution

The proposed solution is to pass each block into individual props, instead of passing them in a separate array, and use the prop name as its handler instead of using its block id. For example, the `shelf` block expects to receive something like this:

```json
{
  "shelf": {
    "blocks": ["product-summary.shelf#anything"]
  }
}
```

And the idea is to turn this into:

```jsonc
{
  "shelf": {
    "props": {
      // (...)
      "ProductSummary": "product-summary.shelf#anything"
    }
  }
}
```

To distinguish regular props from components being passed to slots, the convention we'll use is that **props written in PascalCase should receive blockIds** and will be received by React components as the components themselves. Also, those props will be specified in a new `slots` field added to the interface definitions for each block.

The advantages of doing it this way are basically the following:

- No need for `blocks` attribute while implementing a block in a theme;
- No need for the `composition` field in the interface definition;
- No need for the `allowed` field;
- Any block could be passed to a slot, not only a certain block i.e. `product-summary` or `product-summary.something` in the `shelf`;
- Individual slots will be declared in the `interfaces.json` file, so the API is clearer and users know exactly which slots are available for each block.
- Many single-use blocks might become obsolete, such as  "search-result-layout.desktop".

Another potential benefit is the end of `before`, `after` and `around`. But we are still not sure how would this function without causing a breaking-change.

Also, `children` would still be separate property, so nothing would change in that kind of block.

## Examples

A few practical examples of this change, on how it would change the way themes are written.

### Search Result

Before:

```jsonc
// blocks.json
"search-result-layout": {
    "blocks": [
      "search-result-layout.desktop",
      "search-result-layout.mobile",
      "search-not-found-layout"
    ]
},
```

```jsonc
// interfaces.json
"search-result-layout": {
    "allowed": [
      "search-result-layout.desktop",
      "search-result-layout.mobile",
      "search-not-found-layout"
    ],
    "component": "SearchResultLayout"
},
```

After:

```jsonc
// blocks.json
"search-result-layout": {
    "props": {
      "DesktopLayout": "flex-layout.row#search-result-desktop",
      "MobileLayout": "flex-layout.row#search-result-mobile",
      "NotFoundLayout": "flex-layout.row#search-result-not-found"
    }
},
```

```jsonc
// interfaces.json
"search-result-layout": {
    "component": "SearchResultLayout",
    "slots": ["DesktopLayout", "MobileLayout", "NotFoundLayout"]
},
```

### Footer

Before:

```jsonc
// blocks.json
"footer": {
   "blocks": ["footer-layout.desktop", "footer-layout.mobile"]
},
```

```jsonc
// interfaces.json
"footer": {
    "allowed": [
      "footer-layout.mobile",
      "footer-layout.desktop"
    ],
    "component": "Footer",
    "content": {
      "$ref": "app:vtex.store-footer#/definitions/Footer"
    },
    "render": "client"
},
```

After: 

```jsonc
// blocks.json
"footer": {
   "props": {
      "DesktopLayout": "flex-layout.row#footer-desktop", 
      "MobileLayout": "flex-layout.row#footer-mobile"
    }
},
```

```jsonc
// interfaces.json
"footer": {
    "component": "Footer",
    "content": {
      "$ref": "app:vtex.store-footer#/definitions/Footer"
    },
    "slots": ["DesktopLayout", "MobileLayout"],
    "render": "client"
},
```

## Implementation draft

shelf
  title: 'Destaques'
  ProductSummary: 'product-summary.boladao'

```tsx
const generateSlot = ({ treePath, slotName = 'ProductSummary', slotValue = 'product-summary.shelf' }) => {
  const newTreePath = treePath + / + slotValue
  const extension = __RUNTIME__.extensions[newTreePath]

  const Component = getImplementation(extension.component)
  const isEditable = isComponentEditable()

  let SlotComponent = null
 
  if (isEditable) {
    SlotComponent = (props) => {
      useEffect(() => {
        addDataToElement(newTreePath),
      }, [])

      return <Component {...extension.props} {...props} />
    }
  } else {
    SlotComponent = (props) => <Component {...extension.props} {...props} />
  }

  SlotComponent.displayName = slotName

  return SlotComponent
}

const DynamicSlot = ({ id, children }) => {
  const newTreePath = treePath + '#' + id
  const extension = __RUNTIME__.extensions[newTreePath]

  useEffect(() => {
    addDataToElement(newTreePath),
  }, [])

  return React.Children.map(children, (child) => 
    React.cloneElement(child, {...child.props, extension.props })
  )
}
```

Slot com #
`header/menu/menu-item.root#home`
`header/menu/menu-item.root#home-4234/`

Slot sem #
`header/menu/menu-item.root/`
`header/menu/menu-item.root#4234/`

`header/menu/menu-item.root`
props:
  outras coisas

`header/menu/menu-item.root#{id-do-men}/`
props:
  Submenu: 'submenu.default'

`header/menu/menu-item.root#{id-do-brand}/`
props:
  Submenu: 'submenu.brands'

```tsx
const Menu = ({ navigationId, Item }) {
  const navigation = useNavigation(navigationId)

  return (
    <div>
      {navigation.items.map(item => {
        <DynamicSlot key={item.id} id={item.id}>
          <Item />
        </DynamicSlot>
      })}
    </div>
  )
}
```

**Comment by kaisermann** [comment]
As discussed, for us to be able to differentiate "common" props from "slot" props, the slot naming pattern should follow a pascal case convention, which means they should begin if a uppercase letter

**Comment by lucis** [comment]
In that case, instead of using `ExtensionPoint` to render a specific block, the component would instead receive the `DesktopLayout` prop, for example, already as a component?

One particular thing that I couldn't understand is the reason to use the `props` API to accomplish that, leaving it with two responsibilities. The framework would only try to resolve the value as a block when the key is _PascalCased_? IMO this would add a bit of fraction on DX.

Overall, I like the idea of passing blocks directly to "slots" that the UI will render, it makes more sense than [how we do it today](https://gist.github.com/lucis/d2d4ffa73afd25289ccc53d08c019b62) for cases like that.

**Comment by lbebber** [comment]
> One particular thing that I couldn't understand is the reason to use the props API to accomplish that, leaving it with two responsibilities

@lucis The idea is that, in React, data is already always sent via props; so giving it this responsibility is nothing out of the ordinary, in fact it is making it more React-ish and having one less concept to teach.

The idea for identifying blocks by its casing is that these blocks won't be sent as elements, but as components (i.e. you won't use them like this `<div>{DesktopLayout}</div>`, but like this `<div><DesktopLayout /></div>`, in order to be able to set/override props at the component level) so they will already have to start with upper case by necessity.

**Comment by lbebber** [comment]
One thing we were discussing regarding the syntax though is whether just treating all props that begin with upper case as "slots" would be a breaking change, and/or too magical, and if we should add other means of identifying that "this block accepts slots".

One idea was to make use of the `composition` value already present in the `interfaces` spec (e.g. adding a `composition: slots`)

I think this might be good, because it's safer, and allows better build-time checking

**Comment by lbebber** [comment]
or perhaps being more specific, and declaring each individual slot somehow on `interfaces.json`, so it's both safer and more explicit/less magic 🤔

**Comment by lucis** [comment]
@lbebber I totally understand sending the components as `props` to the component, what I questioned was using the `props` API from our framework, where I would expect to get the exact same object I've passed inside the component. I think it's the same as you described as **"too magical".**

Personally, I find that having a `slots` object like: 
```
"search-result-layout": {
    "props": {
       "maxItems": 5
    },
    "slots": {
      "DesktopLayout": "flex-layout.row#search-result-desktop",
      "MobileLayout": "flex-layout.row#search-result-mobile",
      "NotFoundLayout": "flex-layout.row#search-result-not-found"
    }
}
```
wouldn't add too much to the API and I think it'd be simpler to understand. For example, I know that everything I pass to the `children` array will be resolved as blocks/components.

If you guys decide to take on the `composition` idea, this would even fit better with the "composition `blocks` indicate that the block has a `blocks` property, composition `children` indicated a `children` property..."

**Comment by denisebiscaro** [comment]
Silly question:

How the user will know that in the first example the `ProductSummary` only accepts a few kinds of components -  product-summary  ~family of components - and that the `DesktopLayout` slot may accept ~anything?  Would that information rely only in Documentation?

If so... Thinking about a future when we will be able to ~render the main documentation info directly from the code, wouldn't it make sense to have the information about what each slot accept explicit in some file such as `interfaces.json`?

If not... Where would this information be? 🤔

**Comment by lbebber** [comment]
@lucis I think there are benefits in your suggestion (better separation) but I have a few things against it (some which I think should've been clearer before):
- for someone who only ever uses `blocks.json`(i.e. only customises stores, never creates components), adding a new concept of "slots" is something new to teach, instead of just "this prop accepts a block as a value".
- our intention is to kill `composition`. it was created due to a temporary limitation on the blocks framework, not as a feature we think is worth keeping.
- `blocks.json` might become a "`blocks.tsx`" in the future. in a jsx-like syntax, I think only ever having props and children is more "natural".

**Comment by lbebber** [comment]
@denisebiscaro the idea we are thinking now is to be explicit for each individual slot, as we are going to be for each individual prop: declaring which type each prop accepts, and in the same way declaring which "type" each slot accepts. actually going this way, a "slot" will actually just be a specific type of prop--a prop whose type is "Block", or something of the sort.

I've meandered a bit, but the idea is that each slot would be declared just as each prop is declared. So the question on how it's documented, where it's declared, etc. is the same for both

**Comment by victorhmp** [comment]
@lucis I think we'll go with the idea of adding a `slots` field to `interfaces.json`, it does make it easier to understand, and we're already kinda removing `composition`, `allowed` and even `blocks` with this change, so it's worth the new one.
But the idea of passing components via props, as @lbebber said comes directly from React itself, so I don't think it would cause that much confusion.
I'll update the RFC to accommodate this idea.

**Comment by lucis** [comment]
Nice, @victorhmp and @lbebber!

Do you guys think it's worth it also reviewing the plugins API on the framework? The ~dead~ [Wishlist](https://github.com/vtex-apps/wishlist/blob/master/store/plugins.json) example is a good  one.

**Comment by lbebber** [comment]
it really is worth reviewing @lucis, thanks for bringing attention to it

**Comment by firstdoit** [comment]
This is **very good!** :excited_conan:

> Another potential benefit is the end of before, after and around. But we are still not sure how would this function without causing a breaking-change.

I think this is precisely the **right** moment to propose breaking changes. We want to make stores that are 1-2 orders of magnitude faster than today. We are already investigating lots of deep changes. So... don't be constrained by compatibility right now. Let's align our **vision** first, then we'll discuss what/where we'll break compatibility and how we will migrate.

> actually going this way, a "slot" will actually just be a specific type of prop--a prop whose type is "Block", or something of the sort.

@lbebber the more I read this the more I get used to @tlgimenes' idea - of making the entire thing _just_ TypeScript. 

Overall, this is great and there's one more step we'd have to give in order to really get to this :point_up:, which is... **killing interfaces.json**. Do we really need that? 

_joguei e saí correndo_

**Comment by klzns** [comment]
> @lbebber the more I read this the more I get used to @tlgimenes' idea - of making the entire thing _just_ TypeScript.
> 
> Overall, this is great and there's one more step we'd have to give in order to really get to this , which is... **killing interfaces.json**. Do we really need that?

There's a drawback of using TypeScript which is not a format interpretable by JavaScript, we would need this to be compiled to another format such as JSON Schema to be usable by Site Editor, front end libraries and other tools.

**Comment by lucasecdb** [comment]
I just wanted to add my 2 cents here, but why are we passing the component reference instead of an _element_? Even the [new React APIs](https://reactjs.org/docs/react-api.html#reactsuspense) are being adapted to receive elements because it leans towards better composability, and since our blocks can receive custom props (e.g. `flex-layout.row#search-result-desktop`) it would make more sense to pass the instanced element, with the props already setted, to the underlying block instead of a component reference. What do you think?

**Comment by lbebber** [comment]
@lucasecdb That is so the implementation of the component that receives the slot can override/set certain props, as it is currently done on `<ExtensionPoint />`, if it so wishes.

The idea is that the component receives a wrapped instance of the block, whose wrapper receives props and sends them down to the component, which has its props pre-set by jts `blocks.json` config.

For example:

Tipagem de props já é feita de certa forma via contentSchemas.json.
 
Podemos nos aproveitar dele, ao menos por enquanto, talvez com alguma flag adicional a la isLayout [mais um exemplo de usar enums ao inves de boolean. se isso já fosse um enum era só adicionar mais um valor].


Se uma prop passada para um bloco não existir no schema, ou for de tipo errado, pode dar erro em build time.


Quando uma prop aceita um slot, o type da prop no schema pode ser string (já que nomes de blocos sao strings), e o format poderia ser Block, ou similar.

Por exemplo:

  "DesktopLayout": {
    "title": "Desktop Layout",
    "type": "string",
    "format": "Block"
    "description": "admin/editor.link.href.description"
  },
```

Quando uma prop tem format: Block (ou similar), é feita uma verificação em build time pra ver se tal bloco existe.
Se não existir, dá erro.
Se existir, o componente recebe via essa prop um componente que é um wrapper do bloco que foi passado, que recebe props opcionais pra dar override/passar callbacks/etc, assim como da pra passar props pro ExtensionPoint. Exemplo:

```
  // blocks.json
  header: {
    DesktopLayout: "flex-layout.row#header"
  }
  flex-layout.row#header: {
    props: {
      foo: "bar",
    }
    children: [
      ...
    ]
  }
```

```
  // Header implementation
  const Header = ({ DesktopLayout, MobileLayout }) => {
    const { isMobile } = useDevice()

    if (isMobile && MobileLayout) {
      return <MobileLayout onFoo={handleBar} />
    }

    if (DesktopLayout) {
      return <DesktopLayout onFoo={handleBar} />
    }

    return null
  }
```

```
  // example of generated "DesktopLayout" that is sent to the Header

  const DesktopLayout = props => {
    return (
      <ExtensionPoint
        id="flex-layout.row#header" // <- just for example, not actual implementation
        foo="bar"
        {...props}
      />
    )
  }
```

**Comment by lbebber** [comment]
@lucasecdb I've thought a little more about it though, and since we are intentionally allowing any kind of block in slots, without any expectation of specific types of blocks--unlike `ExtensionPoint`, where we do know what kind of block is being inserted--perhaps it doesn't make sense to try to override/set props to slots. So maybe it doesn't make sense to try to receive components instead of just elements. 🤔
