### ISSUE TITLE
Is it possible to change the buyButton text in the product page?

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/store-discussion#232]
**What are you trying to accomplish? Please describe.**  
I'm trying to change the buyButton text from "Add to cart" to "Add to bag"

**What have you tried so far?**  
Reading the documentation

**Additional info**  
A prop for "text" would be nice for this component

| Account | Workspace |
|---|---|
|`louche`|`dragos`|

**Comment by denisebiscaro** [comment]
Hey @doruradu 

Try using [add-to-cart-button](https://github.com/vtex-apps/add-to-cart-button) component and along with [minicart.v2](https://github.com/vtex-apps/minicart)

There's not an easy way to change the text for now... you should make the steps associated with this recipe - https://vtex.io/docs/recipes/development/overwriting-the-messages-app

It takes sometime to reflect in your store due to cache.

We will add this issue to our backlog in order to make it easier to manage. 

Cheers!

**Comment by doruradu** [comment]
Ok, @denisebiscaro! thanks for the info!
