### ISSUE TITLE
Lazy Load Question

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#240]
I saw in some stores with IO the functionality of lazy load on images. is this already native?

**Comment by denisebiscaro** [comment]
Hey @alextalha ! In order to ensure that your images will be lazy loaded, please follow the guidelines below.
These improvements are not officially released, but they are already being broadly used.
We'll soon release them officially along with other more powerful performance friendly blocks.

## 1 - Add `__fold__` block to your store

- **What is it?**

    This block only loads the content “below the fold” once the user starts scrolling, thus improving initial loading performance.

- **How to use it?**
To use it, just add a `__fold__` block on any template block on your theme (`store.home,` `store.product`, `store.search` ...) . It must be declared for **every template** you want to apply this behavior.

Example of fold block being applied in the Home template:

    
    "store.home": {
    	"blocks": [
    		"carousel#home",
    		"flex-layout.row#deals",
    		"__**fold__**",                      //<------------
    		"shelf#home",
    		"info-card#home",
    		"rich-text#question",
    		"rich-text#link",
    		"newsletter"
    	]
    },
    

In this example, the content from `shelf#home`  and below will only be loaded when the user starts scrolling. 
Alternately, you can set different folds for mobile and desktop, using both `__fold__.desktop` and `__fold__.mobile` blocks on the same page. This strategy is important when the elements shown in the first view are different for desktop and mobile. In the example below, both the `carousel` and the `shelf` are shown on the first paint on the **desktop** mode, and only the `carousel` is shown on **mobile's** first paint:

    "store.home": {
    	"blocks": [
    		"carousel#home",
    		**"__fold__.mobile",                      //<------------**
    		"flex-layout.row#deals",
    		"shelf#home",
    		**"__fold__.desktop",                      //<------------**
    		"info-card#home",
    		"rich-text#question",
    		"rich-text#link",
    		"newsletter"
    	]
    },

- **When to use it?**

It is important to use this block when your page is scrollable, so only the first visible blocks are loaded, and the ones "below the fold" are lazy loaded on scroll.

- **Side-effect, or why it was not implemented as a default behavior:**

Google won't be able to crawl any content below the fold, since they are only loaded *on scroll*. Make sure you add all the SEO-relevant information above the fold when applying this improvement.

## 2 -  `slider-layout`

Make sure you are implementing your Carousels and Shelfs using our new `slider-layout` which has a better performance

[Carousel recipe](https://vtex.io/docs/recipes/layout/building-a-carousel-through-lists-and-slider-layout)

[Shelf recipe](https://vtex.io/docs/components/product/vtex.shelf])


---


One *extra tip* that makes a huge difference on a store's performance is:

##  **Prop `experimentalOptimizeRendering` na app Menu**

- **What is it?**

A prop available on the `menu` component - *experimentalOptimizeRendering*

- **What it does?**

This prop will prevent `submenus` to be loaded until the user interacts with its parent `menu`. 

When using the prop on the main menu, only the first visible menu-items would be loaded on the website, all the others chained`submenu` that contain the others `menu-item` would be **lazy loaded**. This improvement would reduce the total number of loaded blocks in the menu by ~90%.

This prop is applied to the whole chain of `submenus` and `menu-items` that are contained on the `menu` where it was originally declared.

- **Side-effect, or why it was not implemented as a default behavior:**

When this prop is implemented, the google is prevented from crawling the items in the `submenus` that will be lazy loaded, potentially hazarding the Store's SEO. Before implementing it, make sure your SEO strategy is covered by the available content/links on the store's first paint or by its sitemap.

If in doubt, apply this prop only to your **mobile menu**, and keep the desktop's one being rendered fully.

Another option is adapting the way your menu is declared, and then adding this prop only to the `menu` blocks whose chain of `submenus` may be hidden from Google. 

Keep in mind that only the menu's children chained blocks are affected by this prop, other menu blocks outside of that chain won't be unless they also have this prop declared.

**How to implement it?**

**Example:**

    
    "vtex.menu@2.x:menu#electronics":{
       "children": [
          "menu-item#cameras",
          "menu-item#laptops",
          "menu-item#tvs"
        ],
        "props":{
          "orientation": "vertical",
          **"experimentalOptimizeRendering": true   // <------------------**
        }
    }

In this case,  the three `menu-items`' content **will** be visible to google, however, any `submenu,` together with their own chain of blocks, that might be triggered by any of those three `menu-items` **will not.**



-----------

Please let me know if you have any doubts :)
