### ISSUE TITLE
Header and Footer on Account

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#256]
**Describe the bug**

I would like to know how to add the header and footer in / account. both are only shown on mobile and not on the desk

**To Reproduce**
enter in /account

**Screenshots**
![mobile-fensa-account](https://user-images.githubusercontent.com/4852136/77960129-1e830380-72ae-11ea-91e8-5e73e1c24bbc.PNG)
![desk-fensa-account](https://user-images.githubusercontent.com/4852136/77960131-204cc700-72ae-11ea-9953-8282bf163e62.PNG)

** account / workspace ** 
    fensacl  /   store2

**Comment by klzns** [comment]
We have an optimization that when the page is loaded as mobile we don't load the desktop blocks.

So if you open the page as mobile and then resize it to desktop the header and footer blocks will be empty, because we try to render the desktop blocks but they aren't loaded.

If you load the page as desktop the header and footer will load fine.

That is, that's the expected behavior.
