### ISSUE TITLE
Product-kit minicart.v2 Add To Cart Button support addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#257]
**Is your feature request related to a problem? Please describe.**
- Button "BUY KIT" behavior. Description: The product kit isn't added to the minicart.v2, it only appears in checkout's first step as the video shows. Video: (https://nimb.ws/aLchIA)

**Describe the solution you'd like**
- Add a prop to choose the type of buy button that it is going to be render (`minicart.v1` Buy Button or `minicart.v2` Add To Cart Button ) in order to add compatibility with minicart.v2.

**Additional context**

- Component link: https://github.com/vtex-apps/product-kit
- Screenshots: (https://prnt.sc/rmpv6r) (https://prnt.sc/rmpw3a) (https://prnt.sc/rmpxiq).

**Comment by victorhmp** [comment]
Hi @luizgpriolli ! Thanks for the feature request!

Unfortunately, this behavior is expected, and do *not* plan on updating the `vtex.product-kit` app any longer. We don't encourage you to use this app since it does not work properly and will be deprecated very soon (in fact we should've already done this).

Sorry for the inconvenience :(

**Comment by luizgpriolli** [comment]
Hey @victorhmp 

Understood. Thank you very much for such quick feedback.
