### ISSUE TITLE
condition-layout categoryTree not accepting more than one value

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#280]
**Describe the bug**
In the App documentation "condition-layout", it says that the categoryTree option is an array type, but apparently it only accepts one option as a parameter. If I put more than category tree ID, the component that should be rendered by the condition does not appear.

**To Reproduce**
1. I implement the following code (https://flic.kr/p/2iQE9Xc);
2. Select any product at the following addresses https://condition--tackoftheday.myvtex.com/rider/riding-apparel and https://condition--tackoftheday.myvtex.com/home-and-gifts;
3. For "Riding Apparel" products the size chart tab appears and for "Home and Gifts" products does not appear (https://flic.kr/p/2iQzJL5 https://flic.kr/p/2iQE9Ss);
4. Now, if I implement this code: (https://flic.kr/p/2iQE9VD https://flic.kr/p/2iQCt3U https://cl.ly/b6b74c274c82);
5. Select any product at the following addresses https://condition--tackoftheday.myvtex.com/rider/riding-apparel and https://condition--tackoftheday.myvtex.com/home-and-gifts again;
6. You will see that none of the products will have the size-chart tab anymore, the opposite being the correct one. "Riding Apparel" and "Home and Gifts" products should show the size-chart tab according to the last code implemented (https://flic.kr/p/2iQzJK8 https://flic.kr/p/2iQE9Ss).

**Expected behavior**
We hope that when inserting more than one category tree ID, the block present in the condition-layout is rendered. What is not currently happening.

**Additional context**
Workspace where we are performing the tests: https://condition--tackoftheday.myvtex.com.

**Comment by kaisermann** [comment]
Hey @luizgpriolli 👋To check for multiple values inside an array subject, you must define different condition objects instead of passing the possible values in an array in the `object` prop (check the types here https://github.com/vtex-apps/condition-layout/#conditionarray) and define the match type as `any` instead of the default (`all`).

```json
{
  "condition#custom-pdp": {
    "props": {
      "match": "any",
      "conditions": [
        {
          "subject": "categoryTree",
          "verb": "contains",
          "object": 1
        },
        {
          "subject": "categoryTree",
          "verb": "contains",
          "object": 15
        }
      ]
    }
  }
}
```

(Please paste your json here in future issues, it helps a lot 😁. You can use the `<details>` tag to prevent making the issue enormous: https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
