### ISSUE TITLE
bug on tab with shelf

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#284]
**Describe the bug**

in two accounts that use a shelf tab, both stopped displaying the shelf. just runs loading and doesn't display anything

**To Reproduce**
click on the relevant tab and it will not be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/4852136/80710191-d6314e00-8ac4-11ea-8a05-738f70a046a3.png)

**account**: fensa
**workspace**: store2

**Comment by Klynger** [comment]
Hi @alextalha , I'm trying to login in this account but it says that the account doesn't exist

**Comment by alextalha** [comment]
@Klynger 
sorry.  

**account** : fensacl

**Comment by Klynger** [comment]
I fixed the problem in your workspace @alextalha . You have to install an app that implements our search protocol (the one that I installed was the `vtex.search-resolver`).  Even tho could you give me some information about this account? This problem is happening since the creation of the account or just started to happen? Is this account new?

**Comment by alextalha** [comment]
@Klynger 
started this problem yesterday.

**Comment by Klynger** [comment]
Ok, thanks!
