### ISSUE TITLE
Insert  form/input elements

### ISSUE THREAD

**Issue by k-ashok** [vtex-apps/store-discussion#29]
What is the recommended way to insert form/input elements into the page? Which vtex block should be used?

**Comment by klzns** [comment]
@k-ashok what are you trying to achieve?

**Comment by k-ashok** [comment]
> @k-ashok what are you trying to achieve?

![form](https://user-images.githubusercontent.com/52157580/60703960-b969cf80-9f20-11e9-8aa5-e6c357cdcfc7.PNG)

**Comment by saviofelixmuniz** [comment]
@k-ashok currently the only possible way to do this is to use a sandbox app and put your form inside an iFrame. It's in my roadmap to build a custom form component that sends data to MasterData, but it's under development yet.

**Comment by fabiofeichtinger** [comment]
@denisebiscaro do we have a deadline for this feature?

**Comment by blaurenzano** [comment]
Hi, I tried to use the sandbox app to insert a form and when I use the submit button of the form I see this error on the console:
`Blocked form submission to 'https://webto.salesforce.com/servlet/servlet.WebToCase?encoding=UTF-8' because the form's frame is sandboxed and the 'allow-forms' permission is not set.`
How would I set this 'allow-forms' permission?

**Comment by denisebiscaro** [comment]
https://github.com/vtex-apps/store-form
