### ISSUE TITLE
Search page not showing anything. Using default `store-theme` template

### ISSUE THREAD

**Issue by kid-three** [vtex-apps/store-discussion#339]
**What are you trying to accomplish? Please describe.**  
I am troubleshooting as to why nothing is displaying in side any search page in my store.

https://thenorthfacemx.myvtex.com/ 
**links in menu are default and do no go anywhere**

I have installed[ Defualt vstex-store theme](https://github.com/vtex-apps/store-theme).

 It has a `search.jsonc`  file that seems to be correct.

I can see individual products, however when I try to navigate through breadcrumbs, or through the search input all pages return empty 

![image](https://user-images.githubusercontent.com/32473931/87180214-b9c04780-c2a5-11ea-923b-39473113c035.png)

Is this something to do with our setup?  The products we have up there should be complete.

**What have you tried so far?**  
I tired creating a new search.json from scratch with a very simple layout. I tried copying the layouts used in teh VTEX Training courses in github learn.

| thenorthfacemx  | all workspaces
 |
|---|---|
|`your account`|`your workspace`|

**Comment by juliomoreira** [comment]
Hi @kid-three this has happened to me recently in some accounts due to them not having `vtex.search-resolver` installed.

You need to either install `0.x` or `1.x` on your account.

I would recommend you to install `0.x` since `1.x` is intended to be used with VTEX Intelligent Search which would require you a couple more steps to get it working.

@klzns can you please check that? I think it's missing from `vtex.edition-store@2.x` thanks.

**Comment by kid-three** [comment]
This worked, thanks.
