### ISSUE TITLE
Wish-list@1.x billingOptions error

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#355]
**Describe the bug**
Apparently, there is an error in the new update in the `vtex.wish-list@1.x` component, which cannot be linked due to an error in the billingOptions.

**To Reproduce**
1. Go to your code-editor, create a new workspace for your project, install app using: `vtex install vtex.wish-list@1.x`.
2. Add the code `"vtex.wish-list": "1.x"` to your `dependencies` in your `manifest.json` file.
3. Create file `wishlist.jsonc` with default structure as explain it in the documentation.
4. Try to link it in a workspace.
5. See error at the terminal console.

**Expected behavior**
Being able to execute this component in newest version possible. As expected following the pertinent documentation.

**Screenshots**
- billingOptions Error: https://prnt.sc/tpffd4 //// https://prnt.sc/tpgi91
- Version 0.x working fine: https://prnt.sc/tpgg0a //// https://prnt.sc/tpgghz

**Additional context**
Documentations: https://github.com/vtex-apps/wish-list ///// https://github.com/vtex-apps/wish-list/blob/master/manifest.json
As we can see in the master `manifest.json`, the version is on @1.x. So, after we also try to use older version of the component (`vtex.wish-list@0.x`), and apparently in this older version it's works fine.

**Comment by polishq** [comment]
Hi @luizgpriolli, yes, we have added `billingOptions` to the app because we are preparing to offer it on the VTEX App Store. An app that has `billingOptions` cannot be added to the `dependencies` section of another app's manifest. Instead, you must create a new section called `peerDependencies` and include it there. 

To explain further, `dependencies` are installed automatically when you install the app that depend on them, whereas `peerDependencies` must be installed manually before installing the app that depends on them. App Store apps cannot be installed automatically because they have terms and conditions that must be agreed to, therefore they must be included as `peerDependencies`.
