### ISSUE TITLE
Change product delete icon

### ISSUE THREAD

**Issue by chrisar45** [vtex-apps/store-discussion#386]
Can the product delete icon be changed? I'm trying to change the product elminicaion icon and can't find where, since the icon id is "vtex__icon-delete"

I tried to do it through the "icon pack.svg" file, but I can't find the id "vtex__icon-delete"

| Account        | Workspace        |
| -------------- | ---------------- |
| `lyracons` | `test` |

**Comment by victorhmp** [comment]
Hi @chrisar45 !
Yep, it should be possible to change this icon by the same process used to change any other icon.
Take a look at this recipe: https://vtex.io/docs/recipes/style/customizing-your-stores-icons/

Also, the icon id you're looking for is: `hpa-delete`

**Comment by chrisar45** [comment]
mmmmm, i tried, but its not working.

**Comment by chrisar45** [comment]
Tried in my own partner store, but it is for poccarrefourarg

| Account        | Workspace        |
| -------------- | ---------------- |
| `poccarrefourarg` | `chef` |

**Comment by chrisar45** [comment]
Something new

**Comment by chrisar45** [comment]
@victorhmp Something new?

**Comment by victorhmp** [comment]
Hi @chrisar45 !
Sorry for the delay. Apparently there's nothing wrong with the instructions in the recipe... but due to an implementation detail in the `vtex.product-list` app (renders the list of products inside of the `minicart.v2`) this won't work for icons inside of it.

I'll need to open a PR to change this! I'll link this issue to the PR.
