### ISSUE TITLE
Slider-layout adds height during infinite transition

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#428]
**Describe the bug**
The sliderLayout is trembling the page when the arrow to scroll the slider is clicked, passing through the _infinite_ loop, it's adding a class "dib" with a fixed height of 420px, but without it is 356px

**To Reproduce**
1. Go to https://carrefourbr.myvtex.com/
2. Scroll down to "As melhores ofertas para você" section
3. Click on the right arrow until the infinite slider triggers

**Expected behavior**
The page needs to be static when the slider scrolls

**Screenshots**
https://share.getcloudapp.com/7KuL8Qzn

**Desktop environment (please complete the following information, if applicable):**
Windows 10
Google Chrome version 84.0.4147.125

**Additional context**
This bug is affecting all the sliders on the home page under the slideshow.

**Comment by victorhmp** [comment]
Hi @luizgpriolli !

This is actually being caused by the `image` blocks inside of the `slider-layout`. The images inside of those `slider-layout`s are using the `experimentalPreventLayoutShift` prop set to `true`... but the `maxHeight` being passed to these images is equal to `420px`, exactly the value for this fixed height. This `maxHeight` is used by `image` to render a `placeholder` where the actual image would be.

There are two ways to fix this, in the store's theme: either set `experimentalPreventLayoutShift` to `false` in those images or fix the value being passed as `maxHeight` to each image.

**Comment by rayra-alencar** [comment]
Hi @victorhmp 

The adjustments have been made, but it's still blinking. is prop _experimentalPreventLayoutShift_ ok?

![image](https://user-images.githubusercontent.com/28907161/93247479-b85b4180-f764-11ea-8eb5-0748f06e549a.png)

**Comment by victorhmp** [comment]
Hi @rayra-alencar !

Yep, nothing wrong with your code... I've just noticed a bug in the implementation of `list-context.image-list`... this prop is not being passed down to the `Image` component. I'll open a PR to fix this ASAP and mention this issue.

Thanks for the report :)

**Comment by victorhmp** [comment]
Linked in this workspace: https://victormiranda2--carrefourbr.myvtex.com/

**Comment by victorhmp** [comment]
`vtex.store-image@0.5.2` should solve the issue ;)

You will just need to disable `experimentalPreventLayoutShift` is all images and this issue should go away 😄
