### ISSUE TITLE
OrderForm query does not return product with attachment

### ISSUE THREAD

**Issue by despossivel** [vtex-apps/store-discussion#443]
Describe the bug
When you have products in the cart with an bundle item, the GraphQL query does not return undefined, even if you have products in the checkout

To Reproduce

Looking for a product that has an bundle item on the cart
Go to checkout and add the guarantee
Go back to choose more products
see empty cart

 

Could anyone understand this problem?

**Comment by despossivel** [comment]
![image](https://user-images.githubusercontent.com/10657158/93918996-85c0c400-fce3-11ea-9c4b-25d6c20ebfc0.png)


![image](https://user-images.githubusercontent.com/10657158/93918644-06cb8b80-fce3-11ea-9ffd-b38e10742bce.png)

In the order-manage app, in the OrderForm context, the data variable return undefined if there is an attachment to the product

![image](https://user-images.githubusercontent.com/10657158/93918822-48f4cd00-fce3-11ea-9a32-cb069203fa5f.png)

**Comment by despossivel** [comment]
and if I go to checkout and remove attachment, all products are displayed again

![image](https://user-images.githubusercontent.com/10657158/93919165-b0ab1800-fce3-11ea-90a6-0f76848b572f.png)


![image](https://user-images.githubusercontent.com/10657158/93919245-c8829c00-fce3-11ea-9900-be8e2953938a.png)

**Comment by klzns** [comment]
Can provide a link to a development workspace?

**Comment by klzns** [comment]
Are you using the add-to-cart-button or the buy-button?

**Comment by despossivel** [comment]
Workspace I can't provide, but I'm using the addToCart button

**Comment by klzns** [comment]
This bug is caused by the usage of this component. You should change to use the add-to-cart-button instead.

![image](https://user-images.githubusercontent.com/284515/93926297-b3ab0600-fced-11ea-98fc-28af045586a4.png)

This information is available in the minicart docs:
https://vtex.io/docs/components/all/vtex.minicart/

**Comment by despossivel** [comment]
I tested your suggestion and the problem still persists

**Comment by MatheusR42** [comment]
Hello @klzns , we investigate more and find that the problem is on orderform query.

![unknown](https://user-images.githubusercontent.com/16908590/93938992-7dc34d00-fd00-11ea-8ee4-8cabcbcba3ea.png)

To confirm this hypothesis we also created a clean workspace with store-theme and tested. When we add a bundle item the minicart stops to work. Here is the video: https://drive.google.com/file/d/1fZR2ks2DmFVWKYBtT3hjDGXMn1Q5P1Ts/view?usp=sharing

Behind the scene at the checkout we just use this function to add the offer: https://github.com/vtex/vtex.js/tree/master/docs/checkout#addofferingofferingid-itemindex-expectedorderformsections

**Comment by MatheusR42** [comment]
Here is my full orderform:
 https://gist.github.com/MatheusR42/a5ad4a9b0a8fc5e05d9f7ad5f4ccd70c

The buddleitem seller is null. I think that it is optional in old cms.

**Comment by klzns** [comment]
Thanks for the investigation, @MatheusR42! 

We should create a fix at https://github.com/vtex-apps/checkout-graphql. I'll report this issue to the team.

**Comment by despossivel** [comment]
hey, thanks, you guys are awesome
