### ISSUE TITLE
 Error installing the wishlist module

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#460]
**What are you trying to accomplish? Please describe.**  

I would like to install the wishlist module

**What have you tried so far?**  
following the documentation. I added peerdependecy to the manifest. and tried to run the vtex install wish-list

**Additional info**  
![image](https://user-images.githubusercontent.com/4852136/96489792-491ab680-1216-11eb-99c4-4091410217ff.png)
![image](https://user-images.githubusercontent.com/4852136/96489819-55067880-1216-11eb-9c4e-1b242388a7f7.png)

| Account | Workspace |
|---|---|
|`lojaduratex`|`newstore`|

**Comment by klzns** [comment]
Can you run `vtex whoami` please?

**Comment by lucis** [comment]
@alextalha we've identified an issue on our code and are on our way to fix it!

Basically, it's because your user doesn't have "super powers" to install an app with `billingOptions` (like the `vtex.wish-list`) when, in fact, you should be able to do so.

As soon as we ship our solution, I update you here :)

**Comment by lucis** [comment]
It should be working now, @alextalha!

If you have `VTEX IO (Install App)` and `VTEX IO (Buy App)` permissions on your account, you should be good to go :)

Thanks for your patience!
