### ISSUE TITLE
Can't send prop to reviews-and-ratings

### ISSUE THREAD

**Issue by khrizzcristian** [vtex-apps/store-discussion#464]
Hello,

I expanded the application and I created a graph with the number of reviews for each star and it should be displayed by a prop, which by default should be false.

Reviews File:  https://github.com/khrizzcristian/reviews-and-ratings/blob/master/react/Reviews.tsx
```
Line 45:  "showGraphBar: boolean | false"
Line 557: Here will be the condition for display. Right now is  "state.reviews"
```

The idea is that if I check with that prop, the graph never appears. 
If I give console.log(props) after line 331, I don't get that prop.

On the frontend I use:
```
"product-reviews": {
    "props: {
        "showGraphBar": true
    }
}
```

Can anyone help me to fix this ?

Thank you

**Comment by polishq** [comment]
@khrizzcristian Hi, thanks for improving the app!

To be able to accept a prop from the blocks JSON, some additional setup would be needed on the component. However, instead of going in this direction, I would suggest adding this option as an app setting. This would involve:

- updating the AppSettings interface (`react/Reviews.tsx` line 84)
- adding a new settings field in `manifest.json`

You should make the setting a boolean and `false` by default.

Also, out of curiosity, was there a particular store that requested this feature?

**Comment by khrizzcristian** [comment]
Hello. 

Thank you for your answer!
I didn't think to add the option in the settings.

And yes. We have a client who requeated such a chart on his website.

**Comment by polishq** [comment]
Great! I'd be interested to know which client it is, if you're able to share (but I understand if you can't).

By the way, I realized that my instructions above were incomplete. There are a few more files that you'll need to update, which I've edited my earlier reply to reflect.

**Comment by khrizzcristian** [comment]
Thank you for your update 👍 
The client's name is Biasicom
