### ISSUE TITLE
Doubt about user Identifier Extension

### ISSUE THREAD

**Issue by giovanapereira** [vtex-apps/store-discussion#496]
**What are you trying to accomplish? Please describe.**  
Hello! Recently I use the user Identifier Extension to user login with CNPJ and another field, "emailAlteravel". 
Because I need the possibility to user change a email some day. I make this another field to not edit the primary key email.
Buuuuuut, when I ask to edit password, I need to use the primary key e-mail, not the another fields like login. 

**What have you tried so far?**  
I just need a tip or sugestion to how procede with, like "You need to extende the entire login" or something else.

**Additional info**  
![image](https://user-images.githubusercontent.com/26018620/100776136-ef93d300-33e2-11eb-880b-870fa177150a.png)

![image](https://user-images.githubusercontent.com/26018620/100776532-68932a80-33e3-11eb-824e-7cc7108cd86d.png)

| Account | Workspace |
|---|---|
|`portaldolojistahomo`|`giovanalocaliza`|

**Comment by rafarubim** [comment]
Good afternoon @giovanapereira! 😁

**I'm not sure I understand your problem correctly, so I'll start by telling you my interpretation:**

- Your current situation
You're using the `User Identifier Extension` to replace the `Email` field for the `Email/CNPJ` field. Whatever is typed in this field resolves to the actual email used by the platform.

- Your problem
The user types a "modifiable email" to log in, which gets resolved to the "actual email". If he clicks "Forgot my password", then the password recovery email is sent to "actual email". This is not your intention, because you wish it were sent to "modifiable email" instead.

**If my previous assumptions are correct, then here's my answer:**

It's not possible to send the password recovery email to the "modifiable email". The `User Identifier Extension` only allows the replacement of the `Email` input, but it doesn't change the behavior of the app regarding the "actual email".

**So what is my recommendation on how to proceed?**
Unfortunately, I wouldn't recommend extending/replacing the entire login app either. Our whole platform depends on the "actual email". Even if the login app extension did support your custom "modifiable email", you'd have problems with other systems, like "checkout". A lot of systems would still send emails to "actual email".

It's unfortunate, but our platform doesn't support email changes yet. There's not good workaround I can recommend since you'd always have problems in some part of the platform.

**Comment by giovanapereira** [comment]
@rafarubim Thanks for your anwser! My case it's exactly that's you understood. 

I know about "actual email" it's the primary key for everything, but now, the project just need the user to access basic list of product, like a catalog, and the list of orders (not into VTEX) that I receive of an API. 
Anybody can't buy or something else.

I'll chat with my team to solve with another solution this thing!
