### ISSUE TITLE
Error trying to set a secure cookie

### ISSUE THREAD

**Issue by nicolazirilli** [vtex-apps/store-discussion#522]
Hi,
I did a method inside my app that set an HTTP cookie.

I tried to set up this cookie as secure:
![image](https://user-images.githubusercontent.com/77513290/105073572-872ead00-5a87-11eb-9740-df148164f207.png)

but the method response with 500 with this error:

Cannot send secure cookie over unencrypted connection

This happens in dev and production both even if both websites are visited under HTTPS connection. Setting the secure option to false it works

How I cold and answer with a set-cookie header to set a secure cookie?

Thank you

**Comment by lucis** [comment]
@nicolazirilli because of our internal infrastructure, it's possible that VTEX IO requests use HTTP only on internal communication.

To set a secure cookie, can you try using the `Set-Cookie` HTTP Header? More details [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)

Let me know if that works!

**Comment by nicolazirilli** [comment]
thanks @lucis 

In this way it works
