### ISSUE TITLE
Media query breakpoint for tablets.

### ISSUE THREAD

**Issue by sukhan-nisum-com** [vtex-apps/store-discussion#56]
how do we change the media query breakpoint for switching to mobile view? it seems that the default break point does only support mobile phone screen sizes and not tablets.e.g. ipad ...

**Comment by lbebber** [comment]
Could you give a more specific example? Or you mean the website overall?

Currently, you can adjust the breakpoints via the `style.json` file (in `<theme folder>/styles/configs`), under the `customMedia` key. In order to change the tablet breakpoints, you should right now edit the `value` field both under `ns` and `m` (they are in `rem` units, which is `16px` in this case.)


(we are already in the process of adding more tablet-specific breakpoints to our components, though, which should reduce the need for adjusting breakpoints manually)

**Comment by sukhan-nisum-com** [comment]
@ibebber i changed the configuration to following with no effect ...
All i want is to render the mobile view on the tablets as well, right now its showing the desktop view on tablet... See the attached image ...

`"customMedia": [
        { "s": 20 },
        { "ns": {
            "value": 48,
            "minWidth": true
          }
        },
        { "m": {
            "value": 48,
            "minWidth": true
          }
        },
        { "l": {
          "value": 64,
          "minWidth": true
        }
        },
        { "xl": {
            "value": 80,
            "minWidth": true
          }
        }
      ]`

![image](https://user-images.githubusercontent.com/37906464/61066369-d7529b00-a41e-11e9-9da9-d0004c8759ce.png)

**Comment by denisebiscaro** [comment]
@sukhan-nisum-com  Now our breakpoints already consider tablet sizes and phones on landscape mode :)
