### ISSUE TITLE
Order by discount

### ISSUE THREAD

**Issue by gbrsilva** [vtex-apps/store-discussion#651]
**Describe the bug**
The filter `orderBy discount` don't work correctly. Currently the order by is this parameter on link `order=OrderByBestDiscountDESC` but this `orderBy` don't work how expected

**To Reproduce**
Currently -> https://www.medicalshop.pt/vida-diaria?order=OrderByBestDiscountDESC

**Expected behavior**
The filter expected is how this parameter on link `O=OrderByBestDiscountDESC` where products with more discount filtered first

**To Reproduce**
Expected -> https://www.medicalshop.pt/vida-diaria?O=OrderByBestDiscountDESC

**Screenshots**
Currently Image
![Currently Image](https://user-images.githubusercontent.com/87031795/137183875-a231d37d-d51c-4fba-a1ba-b4fd9cc1b57c.png)

Expected Image
![image](https://user-images.githubusercontent.com/87031795/137184163-ec0a9546-8e05-42cc-baff-6364c775a218.png)

** Component Used **
https://github.com/vtex-apps/search-result -> `order-by.v2`

**Comment by thalytafabrine** [comment]
@gbrsilva could you give more details about what is wrong in the search result? for me the order is correct: first items with discount (descending) and then items with no discount

**Comment by gbrsilva** [comment]
@thalytafabrine Items with the lowest value and not the items with the highest discount first are showing.

**Comment by thalytafabrine** [comment]
hello @gbrsilva, I investigated it with my team and we noticed that this store has not been reindexed since August. 
During that time there have been some changes in how our sort boosts are calculated, so this store ended up with old values but applying the new sorting logic. 
We've run an indexing for the entire store and soon the problem should be solved. 
Thank you very much for your patience and any questions you can open a new issue or @ me here again. See you! 👋 🙂
