### ISSUE TITLE
Allow menu items to be managed via Storefront

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#87]
**Is your feature request related to a problem? Please describe.**
Right now there's no way to add, remove or sort items in menus other than via `blocks.json`

**Describe the solution you'd like**
Would be nice to have the option to add more items as well as having a "sorting mode" which enables items to be sorted via drag and drop.

**Comment by lbebber** [comment]
This is already under development! 😄 

We are adding a new way of creating menu items (which is going be the recommended one) via an `items` prop, which is an array of items, instead of having each item be an individual block. This will improve performance and allow them to be edited via Storefront.

Furthermore, we are also developing a `menu-force-accordion` (provisory name) which takes a `menu` block as child, and converts it to an accordion menu. This will help in avoiding the need to edit menu items in both desktop and mobile separately, if both menus are the same.

Will update this when its published

**Comment by denisebiscaro** [comment]
https://vtex.io/docs/releases/2019-week-43-44/menu
