### ISSUE TITLE
 Font renders differently in IO

### ISSUE THREAD

**Issue by leonardkorb** [vtex-apps/store-discussion#94]
**Describe the bug**
After switching from V1 to V2 we felt a difference in font rendering on IO sites. This Issue is of high importance as the client has their own font and is one of the differentials of the site to source. In the print I attached I created a page with a Div and applied the same CSS that I am applying in the component. However it is clear that the platform is rendering the different font and leaving the site out of layout and distorting the expected behavior. This same behavior happened in BrassBell store that we had similar problems related to border color and text due to css rendering.

**Expected behavior**
Like in printscreen

**Screenshots**
https://prnt.sc/oq7axfprint:https://prnt.sc/oq7b07

**Comment by lbebber** [comment]
Hi @leonardkorb, do you have links to workspaces for V1 and V2? I think it'd be better for identifying the differences.

**Comment by leonardkorb** [comment]
Only in v2:
https://calvinkleinnew.myvtex.com/

**Comment by lbebber** [comment]
Sorry, not sure if I get it without comparison with the previous version.

It's different in what sense? Is the vertical alignment off, or is it breaking line when it shouldn't, or is the font thicker/lighter, or something else?

**Comment by leonardkorb** [comment]
Changes the font thickness and some colors are different.

**Comment by pedrohenriqueoliveira** [comment]
@leonardkorb I've created a div just for testing and it looks like the styles of "JUST LANDED" are coming from the `override.css` stylesheet. 

![image](https://user-images.githubusercontent.com/19555647/65174721-d3975200-da27-11e9-9b7f-73e7afd97184.png)

If you want the texts to appear like in your local example, you have two options: 

1) Change the default styles of your page in the `style.json` file, inside the configs folder.
2) Create specific css files to override the default styles following the `{{vendor}}.{{block}}.css` name format. 

You can find more details about how to customize styles in our documentation: https://vtex.io/docs/getting-started/build-stores-with-vtex-io/5

I think the problem it's not in the font itself, since its the same rendered in your workspace and in your example. You have to write the right css properties in the `style.json` or in your custom stylesheets to make the text look like your local test.
